-- +goose Up
CREATE TABLE users (
    user_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(512) NOT NULL,
    password varchar(100) NOT NULL,
    is_admin smallint DEFAULT '0',
    PRIMARY KEY(user_id),
    UNIQUE (email)
);

-- +goose Down
DROP TABLE users;
