# test yaml config

api:
    protocol: http
    domain: localhost
    port: 8080
    debug: true
    cors_domains:
        - http://localhost:8080
db:
    table: test
    host: 127.0.0.1
    user: root
    password: 123456
    max_connections: 140
    max_idle_connections: 70